
- name: install common packages
  yum:
    name: 
      - curl
      - socat
      - bc
      - net-snmp
    state: present

- name: install zabbix agent package
  yum:
    name:
      - zabbix-agent
      - zabbix-sender
    state: present

- name: copy zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent

- name:
  service:
    enabled: yes
    name: zabbix-agent
    state: started
